### ISSUE TITLE
log handler error on Linux environment

### ISSUE THREAD

**Issue by narasimha18sv** [beelit94/python-terraform#10] opened 2017-06-22 03:03 UTC
In Windows environment python-terraform is working properly but when I try the same in the linux getting the below error
No handlers could be found for logger "python_terraform"

After manually updating the log handler in __init__.py file it worked properly. 
handler = logging.StreamHandler()
log.addHandler(handler)

**Comment by beelit94** [comment] 2017-06-22 17:28
Hi @narasimha18sv I can't reproduce this on my linux box,
Can I have your python version, os platform version?
It will be more helpful if you could provide a simple script that could reproduce this issue on your environment.

**Comment by narasimha18sv** [comment] 2017-06-22 18:15
https://github.com/oracle/terraform-provider-baremetal/tree/master/docs/examples/compute/single_instance 
the above is the terraform script I am executing. and python version is 2.7.5

**Comment by beelit94** [comment] 2017-06-23 21:12
@narasimha18sv I still can't reproduce the issue on 2.7.5, could I have the python script that where you import python_terraform?

**Comment by maxadamo** [comment] 2017-08-25 15:21
I have the same issue. 
it work if I run it from the command line (for instance using iron python), but it doesn't work from the script.
I worked it around by adding:
`logging.basicConfig()`

you can check my script here (line 229): 
https://github.com/maxadamo/terraformware/blob/master/bin/terraformware

**Comment by beelit94** [comment] 2017-08-28 18:46
@maxadamo @narasimha18sv I think I figure out the fix. Logging module need at least one handler configured. plz check https://github.com/beelit94/python-terraform/pull/20

**Comment by beelit94** [comment] 2017-08-28 18:47
Fixed in https://github.com/beelit94/python-terraform/pull/20

**Closed** 2017-08-28 18:47 UTC
